# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb5c9b4132a8f3042614de361cff6bcf9249b906b83a0f3a9a35abe4e9f74bba6aa81f77038b1873e2dc48fa39fad5d3ea7e97148b67d5096027d63cbbc226c

test:
  secret_key_base: 49c94e4adc2e84dcc40b7539e501fb8ead322d88357c352e6ce668d7200fb238018eb6c944cd88fae052d25650679aa100da3b1bb6143678615ccf058fbc0bd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
